### PR TITLE
show texts justified

### PR DESCRIPTION
**Pull request by MasoodRezazadeh**
جادی این یه استایل سادس که خطوط متن رو همتراز می کنه

### CODE REVIEW

**Review by mh-hsan — APPROVED** [review]

**Comment by danialbehzadi** [comment]
But why?

**Comment by MasoodRezazadeh** [comment]
> But why?

i think justified texts are easier to human eye when all paragraphs follow same shape and blocky style.
however i closed it since it was open since 2017 and no one cared 😁

**Comment by mh-hsan** [comment]
- [ ] مالرمككك__________

**Comment by mh-hsan** [comment]
> - [ ] مالرمككك__________

**Pull request closed without merging**
